// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { Nullable } from "@/shared/types/utils";
import type { Profile } from "./Profile";

export type Config = {
  profiles: Array<Profile>;
  selectedProfileId: Nullable<number>;
};

