// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModifierKey } from "./ModifierKey";

export type KeyCombination = { modifiers: Array<ModifierKey>, key: string, };
