// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyCombination } from "./KeyCombination";
import type { SequenceStep } from "./SequenceStep";

export type Macro = {
  id: number;
  name: string;
  trigger: KeyCombination;
  sequence: Array<SequenceStep>;
};

