// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { FunctionKey } from "./Key";
import type { Macro } from "./Macro";

export type Profile = {
  id: number;
  name: string;
  functionKey: FunctionKey | null;
  macros: Array<Macro>;
};

