export enum MacroActionType {
  // Profile actions
  SELECT_PROFILE = "SELECT_PROFILE",
  TOGGLE_PROFILE = "TOGGLE_PROFILE",
  ADD_PROFILE = "ADD_PROFILE",
  UPDATE_PROFILE = "UPDATE_PROFILE",
  DELETE_PROFILE = "DELETE_PROFILE",
  SET_PROFILES = "SET_PROFILES",
  
  // Macro actions
  SELECT_MACRO = "SELECT_MACRO",
  ADD_MACRO = "ADD_MACRO",
  UPDATE_MACRO = "UPDATE_MACRO",
  DELETE_MACRO = "DELETE_MACRO",
  UPDATE_MACRO_SEQUENCE = "UPDATE_MACRO_SEQUENCE",
  
  // Step actions
  ADD_STEP = "ADD_STEP",
  UPDATE_STEP = "UPDATE_STEP",
  DELETE_STEP = "DELETE_STEP",
}